### ISSUE TITLE
GG,好久没更新了。

### ISSUE THREAD

**Issue by Jiuyong** [numbbbbb/progit-zh-pdf-epub-mobi#2]
现在貌似 git 已经出到 2.1 了，书不知道更新了没有，要是有空的话，还是更新下吧，毕竟“百众期待”（截止发稿时为止，113 Star ）呢~

**Comment by diyzzz** [comment]
linux上的pandoc转格式，**真**复杂，我折腾过一次，导出来全乱码了：）

**Comment by numbbbbb** [comment]
多谢 @diyzzz 提醒，我加到 README 中。
